config/routes.rb
Paidan::Application.routes.draw do
  resources :docs
    
  resources :deliveries do
    collection do
      get 'deliverying'
      get 'delivered'
      
      get 'edit_delivery'
      post 'save_address'
      post 'shipping_in_volume'
      
      get 'print_expresses'
      get 'print_goods'
    end
  end

  resources :customers do
    collection do 
      get 'level_setting'
      post 'save_level_setting'
    end
  end

  resources :products do
    member do
    end
    
    collection do
      get 'select_category'
      get 'category_children'
    end
  end

  resources :suppliers do
    member do
      get 'follow'
      put 'save_follow'
    end
  end
  
  resources :tasks do
  end
  
  resources :orders do
    member do
      get 'check'
      put 'save_check'
      
      get 'page'
      put 'save_page'

      get 'toggle_pass'
    
      post 'close'
    end
    
    collection do 
      get 'waiting_pay'
      get 'waiting_delivery'
      get 'delivery'
      get 'refunding'
      get 'successed'
      get 'need_comment'
      get 'closed'
      get 'three_months_ago'
      
      get 'delivery'
      
      get 'sync'
      get 'do_sync'
      
      get 'update_ship_fee'
      get 'remark'
    end
  end
  
  resources :auth do
    collection do 
      get 'bind_jingdong'
      get 'bind_taobao'
      get 'bind_paipai'
      get 'bind_yihaodian'
      get 'bind_vjia'
    end
  end
  
  resources :dashboard do
    collection do
      get 'recent_datas'
    end
  end
  
  scope 'settings' do
    resources :shops
    resources :delivery_templates
  end
    
  resources :partners
  
  match 'login' => 'partners#login', :as => :login
  match 'check_login' => 'partners#check_login', :as => :check_login
  match 'register' => 'partners#register'
  match 'logout' => 'partners#logout', :as => :logout  

  match 'import' =>  'orders#import'
  match 'do_import' => 'orders#do_import'
  match 'import_sent' =>  'orders#import_sent'
  match 'do_import_sent' => 'orders#do_import_sent'
  
  match 'taobao_callback' => 'auth#taobao_callback'
  match 'paipai_callback' => 'auth#paipai_callback'
  match 'jingdong_callback' => 'auth#jingdong_callback'
  
  root :to => 'dashboard#index'

end

app/models/user.rb
# encoding: utf-8

class User < ActiveRecord::Base

  ROLES = {
    :default => 0,
    :admin => 10,
  }
  
  PERMISSIONS = {
    :edit_bill    => '录单', 
    :audit        => '审核',
    :edit         => '编辑',
    #:audit_sample => '样品审核',
    #:user_manage  => '用户管理',
  }
  
  PERMISSIONS.keys.each do |key|
    define_method "can_#{key}?" do
      permissions.to_s.split(',').include? key.to_s
    end
  end
  
  attr_accessor :password_confirmation

  validates_presence_of :username, :password, :register_code, :phone
  validates_uniqueness_of :username
  validates_length_of :username, :within => 4..20, 
    :too_long => "太长，最多20位", :too_short => "太短，最少4位"
  validates_length_of :password, :within => 6..20, 
    :too_long => "太长，最多20位", :too_short => "太短，最少6位"
  
  validates :password, :confirmation => true
  validates :password_confirmation, :presence => true

  has_one :setting, :class_name => 'UserSetting', :foreign_key => 'user_id'
  has_many :shops
  has_many :delivery_templates, :class_name => 'DeliveryTemplate'
  has_many :products
  has_many :skus
  has_many :orders
  has_many :customers
  has_many :delivery_templates
  has_many :day_datas
  
  validate do
    errors.add(:register_code, "不正确") unless RegisterCode.valid?(register_code)
  end
  
  before_create do
    generate_password
  end
  
  after_create do
    PLATFORMS.each do |key, value|
      Shop.create(:platform_id => value[:id], :user_id => self.id, :shop_name => value[:name])
    end
    
    RegisterCode.find_by_code(register_code).update_attribute(:is_available, :false)
    UserSetting.create(:user_id => id, :status => 'new_user')
  end
  
  # 生成salt和密码
  def generate_password
    self.salt = SecureRandom.hex(4)
    self.password = Digest::MD5.hexdigest("#{password}#{salt}")
  end
  
  def need_init?
    setting.nil? or setting.status == 'new_user'
  end
  
  class << self

    # 验证
    def valid_by_username_and_password?(username, password)
      user = find_by_username(username)
      return false unless user

      user.password == Digest::MD5.hexdigest("#{password}#{user.salt}") ? user : false
    end
    
  end
end

app/views/users/login.html.erb
<h1>
  登录
</h1>

<% unless flash[:notice].blank? %>
  <div class="alert alert-error">
    <%= flash[:notice] %>
  </div>
<% end %>

<%= form_for(@user, :url => check_login_path, :html => {:class => 'form-horizontal'}) do |f| %>
  
  <div class="control-group">
    <label class="control-label" for="focusedInput">用户名</label> 
    <div class="controls">
      <%= f.text_field :username, :class => 'span2' %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">密码</label>
    <div class="controls">
    <%= f.password_field :password, :class => 'span2' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "登录", :class => "btn btn-primary" %>&nbsp;&nbsp;&nbsp;&nbsp;
    没有账号？
    <%= link_to '注册', register_path %>
  </div>
<% end %>

app/views/users/register.html.erb
<h1>
  注册
</h1>

<%= form_for(@user, :url => users_path, :html => {:class => 'form-horizontal'}) do |f| %>
  <% unless f.error_messages.blank? %>
    <div class="alert alert-error">
      <%= f.error_messages %>
    </div>
  <% end %>
  
  <div class="control-group">
    <label class="control-label" for="focusedInput">用户名</label> 
    <div class="controls">
      <%= f.text_field :username, :class => 'span2' %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">密码</label>
    <div class="controls">
    <%= f.password_field :password, :class => 'span2' %>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">确认密码</label>
    <div class="controls">
    <%= f.password_field :password_confirmation, :class => 'span2' %>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label">电话</label>
    <div class="controls">
    <%= f.text_field :phone, :class => 'span2' %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">注册码</label>
    <div class="controls">
    <%= f.text_field :register_code, :class => 'span2' %> 
    <%= link_to '获取注册码', '#' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit " 注册 ", :class => "btn btn-primary" %> &nbsp;&nbsp;&nbsp;&nbsp;
    已有账号？
    <%= link_to '登录', login_path %>
  </div>
<% end %>