config/routes.rb
Paidan::Application.routes.draw do
  resources :docs
    
  resources :deliveries do
    collection do
      get 'deliverying'
      get 'delivered'
      
      get 'edit_delivery'
      post 'save_address'
      post 'shipping_in_volume'
      
      get 'print_expresses'
      get 'print_goods'
    end
  end

  resources :customers do
    collection do 
      get 'level_setting'
      post 'save_level_setting'
    end
  end

  resources :products do
    member do
    end
    
    collection do
      get 'select_category'
      get 'category_children'
    end
  end

  resources :suppliers do
    member do
      get 'follow'
      put 'save_follow'
    end
  end
  
  resources :tasks do
  end
  
  resources :orders do
    member do
      get 'check'
      put 'save_check'
      
      get 'page'
      put 'save_page'

      get 'toggle_pass'
    
      post 'close'
    end
    
    collection do 
      get 'waiting_pay'
      get 'waiting_delivery'
      get 'delivery'
      get 'refunding'
      get 'successed'
      get 'need_comment'
      get 'closed'
      get 'three_months_ago'
      
      get 'delivery'
      
      get 'sync'
      get 'do_sync'
      
      get 'update_ship_fee'
      get 'remark'
    end
  end
  
  resources :auth do
    collection do 
      get 'bind_jingdong'
      get 'bind_taobao'
      get 'bind_paipai'
      get 'bind_yihaodian'
      get 'bind_vjia'
    end
  end
  
  resources :dashboard do
    collection do
      get 'recent_datas'
    end
  end
  
  scope 'settings' do
    resources :shops
    resources :delivery_templates
  end
    
  resources :partners
  
  match 'login' => 'partners#login', :as => :login
  match 'check_login' => 'partners#check_login', :as => :check_login
  match 'register' => 'partners#register'
  match 'logout' => 'partners#logout', :as => :logout  

  match 'import' =>  'orders#import'
  match 'do_import' => 'orders#do_import'
  match 'import_sent' =>  'orders#import_sent'
  match 'do_import_sent' => 'orders#do_import_sent'
  
  match 'taobao_callback' => 'auth#taobao_callback'
  match 'paipai_callback' => 'auth#paipai_callback'
  match 'jingdong_callback' => 'auth#jingdong_callback'
  
  root :to => 'dashboard#index'

end

app/models/customer.rb
# encoding: utf-8

class Customer < ActiveRecord::Base

  has_many :contacts
  belongs_to :user
  
  LEVELS = {
    1 => {
      :name => '普通客户',
      :color => '',
    },
    2 => {
      :name => '高级客户',
      :color => 'green',
    },
    3 => {
      :name => 'VIP客户',
      :color => 'red',
    },
    4 => {
      :name => '至尊VIP客户',
      :color => 'orange',
    },
  }

  before_save do |customer|
    CustomerLevel.order('level').limit(LEVELS.size).each do |l|
      if customer.total_amount >= l.total_amount or customer.total_orders >= l.total_orders
        customer.level = l.level
      end
    end
  end
  
  def human_level
    "<span style='color:#{LEVELS[level.to_i][:color]}'>#{LEVELS[level.to_i][:name]}</span>"
  end
  
  # 是否已经记录过这个订单的地址？
  def recorded_address?(order)
    contacts.each do |contact|
      return true if contact.human_address == order.human_address
    end
    
    false
  end

  class << self
        
    def init_from_orders(current_user_id)
      Order.where(:user_id => current_user_id).find_each(:batch_size => 2000) do |order|
        customer = Customer.find_by_user_outer_id(order.user_outer_id)
        
        if customer
          customer.total_amount = customer.total_amount + order.payment
          customer.total_orders = customer.total_orders + 1
        else
          customer = Customer.new(
            :user_id => current_user_id,
            :user_outer_id => order.user_outer_id,
            :total_amount => order.payment,
            :total_orders => 1,
            :platform_id => order.platform_id
          )
        end
        
        customer.save
        
        unless customer.recorded_address?(order)
          Contact.create(
            :user_id => current_user_id,
            :customer_id => customer.id,
            :name => order.name,
            :mobile => order.mobile,
            :phone => order.phone,
            :email => order.email,
            :state => order.state,
            :city => order.city,
            :district => order.district,
            :zip => order.zip,
            :address => order.address
          )
        end
      end
    end
    
  end
end

app/controllers/customers_controller.rb
# coding: UTF-8
class CustomersController < ApplicationController
  
  def index
    @customers = @current_user.customers.order('id DESC').paginate(:page => params[:page], :per_page => 20)

    @taobao_customers = @current_user.customers.count(:conditions => ['platform_id = ?', PLATFORMS[:taobao][:id]])
    @paipai_customers = @current_user.customers.count(:conditions => ['platform_id = ?', PLATFORMS[:paipai][:id]])
    @jingdong_customers = @current_user.customers.count(:conditions => ['platform_id = ?', PLATFORMS[:jingdong][:id]])
    
    @level_nums = {}
    @customer_levels = CustomerLevel.all
    @customer_levels.each do |l|
      @level_nums[l.level] = @current_user.customers.count(:conditions => ['level = ?', l.level])
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end

  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json
    end
  end
  
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json
    end
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to(customers_path, :notice => 'Customer 创建成功。') }
        format.json
      else
        format.html { render :action => "new" }
        format.json
      end
    end
  end
  
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to(customers_path, :notice => 'Customer 更新成功。') }
        format.json
      else
        format.html { render :action => "edit" }
        format.json
      end
    end
  end
  
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to(customers_path,:notice => "删除成功。") }
      format.json
    end
  end
  
  def level_setting
    @levels = CustomerLevel.order('level').limit(4)
    logger.debug "=====levels=======" % @levels.inspect
  end
    
  def save_level_setting
    logger.debug params[:level].inspect
    params[:level].each do |level_id, level_attributes|
      CustomerLevel.find_by_id(level_id).update_attributes(level_attributes)
    end
    
    redirect_to level_setting_customers_path, :notice => '保存成功'
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_base.html.erb
<%= content_for :base_sitemap do %>
<a href="<%= customers_path %>">customers</a> » 
<% end %>
<%= content_for :styles do %>
<% end %>

app/views/customers/_form.html.erb
<div id="product-form" class="form">
  <%= form_for(@customer, 
    :url => (@customer.id.blank? ? customers_path : customer_path(@customer)), :html => {:class => 'form-horizontal'}) do |f| %>
  
    <% unless f.error_messages.blank? %>
      <div class="alert alert-error">
        <%= f.error_messages %>
      </div>
    <% end %>

    <div class="control-group">
      <label class="control-label">顾客姓名</label>
      <div class="controls">
        <%= f.text_field :name, :class => 'span2 ' %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">总消费金额</label>
      <div class="controls">
        <%= f.text_field :total_amount, :class => 'span2 ' %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">总订单数</label>
      <div class="controls">
        <%= f.text_field :total_orders, :class => 'span2 ' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit "提交", :class => "btn btn-success" %>&nbsp;&nbsp;
      <%= link_to '取消', customers_path, :class => 'btn' %>
    </div>
  <% end %>
</div>

app/views/customers/_sidebar.html.erb
<div class="well" style="padding: 12px 0;">
  <ul class="nav nav-list">
    
    <li class="<%= ['index', 'show', 'edit'].include?(action_name) ? 'active' : '' %>">
      <a href="/customers"><i class="icon-white "></i> 客户管理 </a>
    </li>
    <li class="<%= action_name == 'inde' ? 'active' : '' %>">
      <a href="/customers"><i class="icon-white "></i> 客户关怀 </a>
    </li>
    <li class="<%= action_name == 'level_setting' ? 'active' : '' %>">
      <a href="/customers/level_setting"><i class="icon-white "></i> 客户级别定义 </a>
    </li>
  </ul>
</div>

<%= render 'shared/bulletin_board' %>
<%= render 'shared/fast_tools' %>

app/views/customers/edit.html.erb
<div class='row'>
  <div class='span2'>
    <%= render 'sidebar' %>
  </div>
  
  <div class='span10'>
    <div class="tools" style='margin:10px 0;'>
      <%= link_to '<-返回客户管理页', customers_path %>
    </div>
    
    <h3>修改顾客信息</h3>
    <br/>

    <%= render 'form' %>
  </div>
</div>

app/views/customers/index.html.erb
<div class='row'>
  <div class='span2'>
    <%= render 'sidebar' %>
  </div>  
  
  <div class='span10'>

    <div class="tools" style='margin:10px 0;'>
      <h3>各平台用户数</h3>
      淘宝客户：
      <strong><%= @taobao_customers %></strong>&nbsp;&nbsp;
      拍拍客户：
      <strong><%= @paipai_customers %></strong>&nbsp;&nbsp;
      京东客户：
      <strong><%= @jingdong_customers %></strong>&nbsp;&nbsp;
        <br/><br/>
      
      <h3>各级别用户数</h3>
      <% @customer_levels.each do |l| %>
        <%= l.name %>：
        <strong><%= @level_nums[l.level]%></strong>&nbsp;&nbsp;
      <% end %>
    </div>

    <div id="products">
  
      <table class="table table-striped">
        <thead>
        <tr>
          <th width=''>客户id</th>
          <th width=''>客户级别</th>
          <th width=''>总消费金额</th>
          <th width=''>总订单数</th>
          
          <th width=''></th>
        </tr>
        </thead>

        <tbody>
        <% @customers.each do |item| %>
        <tr>
          <td>
            <%= raw human_platform(item.platform_id) %>&nbsp;
            <%= link_to customer_path(item.id) do %>
              <%= item.user_outer_id %> 
            <% end %>
          </td>
          <td> <%= raw item.human_level %> </td>
          <td> <%= item.total_amount %> </td>
          <td> <%= item.total_orders %> </td>
          
          <td>
            <!-- <div style='display: inline;'>
              <%= link_to '详情', customer_path(item.id) %>
              <%= link_to '修改', edit_customer_path(item.id) %>
                &nbsp;&nbsp;
              <%= link_to '删除', customer_path(item.id), :method => :delete, :style => 'color:#999;', :confirm => '确定删除吗?' %>
            </div> -->
          </td>
        </tr>
        <% end %>

        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/customers/level_setting.html.erb
<div class='row'>
  <div class='span2'>
    <%= render 'sidebar' %>
  </div>  
  
  <div class='span10'>

    <div class="tools" style='margin:10px 0;'>
    </div>

    <div id="products" style='width:60%;'>
      
      <%= form_for :setting, :url => save_level_setting_customers_path do |f|%>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th></th>
              <th>总消费金额要达到多少元</th>
              <th>或总订单数要达到多少笔</th>
            </tr>
          </thead>

          <tbody>
            <% @levels.each do |level| %>
            <tr>
              <td><strong><%= level.name %></strong></td>
              <td><input type='text' name="level[<%=level.id%>][total_amount]" class='span1' value='<%=level.total_amount%>'/> 元</td>
              <td><input type='text' name="level[<%=level.id%>][total_orders]" class='span1' value='<%=level.total_orders%>'/> 笔</td>
            </tr>
            <% end %>
           
          </tbody>
        </table>
        
        <input type='submit' value='  保存  ' class='btn btn-success'/>
      <% end %>

    </div>
  </div>
</div>

app/views/customers/new.html.erb
<div class='row'>
  <div class='span2'>
    <%= render 'sidebar' %>
  </div>
  
  <div class='span10'>
    <div class="tools" style='margin:10px 0;'>
      <%= link_to '<-返回客户管理页', customers_path %>
    </div>
    
    <h3>录入顾客信息</h3>
    <br/>

    <%= render 'form' %>
  </div>
</div>

app/views/customers/show.html.erb
<div class='row'>
  <div class='span2'>
    <%= render 'sidebar' %>
  </div>
  
  <div class='span10'>
    <div class="tools" style='margin:10px 0;'>
      <%= link_to '<-返回客户管理页', customers_path %>&nbsp;&nbsp;
      <!-- <%= link_to '修改基本信息', edit_customer_path(@customer), :class => "" %> -->
    </div>
    
    <h2>客户信息</h2>
    <br/>
    
    <% if notice %>
    <div class="alert alert-success">
      <a class="close" data-dismiss="alert">×</a>
      <strong><%= notice %></strong>
    </div>
    <% end %>
    
    <div id="customer" style='margin-left:20px;margin-bottom:20px;'>
      <p style='font-size:16px;'>
        <b>客户id：</b>
        <%= @customer.user_outer_id %>&nbsp;&nbsp;
        <b>级别：</b>
        <%= raw @customer.human_level %>
        <br/><br/>
        <b>总消费金额：</b>
        <%= @customer.total_amount %>&nbsp;&nbsp;
        <b>订单数：</b>
        <%= @customer.total_orders %>&nbsp;&nbsp;
      </p>
    </div>
    
    <h3>联系方式</h3>
    
    <table class="table table-striped" style='margin-left:20px;'>
      <thead>
        <tr>
          <th width='80'>姓名</th>
          <th width='120'>电话</th>
          <th width=''>地址</th>
          <th width=''></th>
    
          <th width=''></th>
        </tr>
      </thead>

      <tbody>
      <% @customer.contacts.each do |item| %>
      <tr>
        <td>
          <%= item.name %> 
        </td>
        <td> <%= item.mobile %> , <%= item.phone %> </td>
        <td> <%= item.state %> <%= item.city %> <%= item.district %> <%= item.address %> , 
          <%= item.zip %></td>
        <td></td>
        
        <td>
        </td>
      </tr>
      <% end %>

      </tbody>
    </table>
  </div>
</div>