config/routes.rb
Paidan::Application.routes.draw do
  resources :docs
    
  resources :deliveries do
    collection do
      get 'deliverying'
      get 'delivered'
      
      get 'edit_delivery'
      post 'save_address'
      post 'shipping_in_volume'
      
      get 'print_expresses'
      get 'print_goods'
    end
  end

  resources :customers do
    collection do 
      get 'level_setting'
      post 'save_level_setting'
    end
  end

  resources :products do
    member do
    end
    
    collection do
      get 'select_category'
      get 'category_children'
    end
  end

  resources :suppliers do
    member do
      get 'follow'
      put 'save_follow'
    end
  end
  
  resources :tasks do
  end
  
  resources :orders do
    member do
      get 'check'
      put 'save_check'
      
      get 'page'
      put 'save_page'

      get 'toggle_pass'
    
      post 'close'
    end
    
    collection do 
      get 'waiting_pay'
      get 'waiting_delivery'
      get 'delivery'
      get 'refunding'
      get 'successed'
      get 'need_comment'
      get 'closed'
      get 'three_months_ago'
      
      get 'delivery'
      
      get 'sync'
      get 'do_sync'
      
      get 'update_ship_fee'
      get 'remark'
    end
  end
  
  resources :auth do
    collection do 
      get 'bind_jingdong'
      get 'bind_taobao'
      get 'bind_paipai'
      get 'bind_yihaodian'
      get 'bind_vjia'
    end
  end
  
  resources :dashboard do
    collection do
      get 'recent_datas'
    end
  end
  
  scope 'settings' do
    resources :shops
    resources :delivery_templates
  end
    
  resources :partners
  
  match 'login' => 'partners#login', :as => :login
  match 'check_login' => 'partners#check_login', :as => :check_login
  match 'register' => 'partners#register'
  match 'logout' => 'partners#logout', :as => :logout  

  match 'import' =>  'orders#import'
  match 'do_import' => 'orders#do_import'
  match 'import_sent' =>  'orders#import_sent'
  match 'do_import_sent' => 'orders#do_import_sent'
  
  match 'taobao_callback' => 'auth#taobao_callback'
  match 'paipai_callback' => 'auth#paipai_callback'
  match 'jingdong_callback' => 'auth#jingdong_callback'
  
  root :to => 'dashboard#index'

end

app/models/delivery_template.rb
# encoding: utf-8

class DeliveryTemplate < ActiveRecord::Base
  
  validates :template, :presence => true
  validates :name, :presence => true
  validates :width, :inclusion => { :in => 200..400, :message => "必须在200mm-400mm之间"}
  validates :height, :inclusion => { :in => 100..300, :message => '必须在100mm-300mm之间'}
  
  belongs_to :user
  
  def human_default
    default ? '默认' : ''
  end
end

app/controllers/delivery_templates_controller.rb
# encoding: utf-8

class DeliveryTemplatesController < ApplicationController  
  
  def index
    @templates = @current_user.delivery_templates
  end
  
  def new
    @template = @current_user.delivery_templates.new(:width => '300', :height => '140')
    logger.debug LOGISTICS_COMPANIES.to_json
  end
  
  def create
    # options = {}
    # params[:field_position].values.each do |field, position|
    #   options[field] = position.gsub('px', '')
    # end

    @template = DeliveryTemplate.new(params[:delivery_template])
    @template.options = params[:field_position].values.to_json
    @template.fields = params[:fields].values.to_json
    @template.user_id = @current_user.id
    
    if @template.save
      redirect_to delivery_templates_path, :notice => '保存成功'
    else
      render :action => new
    end
  end
  
  def edit
    @template = DeliveryTemplate.find(params[:id])
    @options = JSON.parse(@template.options).map { |item| class_eval(item) }.to_json
  end

  def update
    params[:delivery_template][:options] = params[:field_position].values.to_json
    
    @template = DeliveryTemplate.find(params[:id])
    @template.fields = params[:fields].values.to_json
        
    logger.debug "url=======%s" % edit_delivery_template_path(@template.id)
    if @template.update_attributes(params[:delivery_template])
      redirect_to delivery_templates_path, :notice => '保存成功'
    else
      @options = JSON.parse(@template.options).map { |item| class_eval(item) }.to_json
      render :action => :edit
    end
  end
  
  def destroy
    @template = DeliveryTemplate.find(params[:id])
    @template.destroy

    redirect_to(delivery_templates_path, :notice => "删除成功。")
  end
end

app/helpers/delivery_templates_helper.rb
module DeliveryTemplatesHelper
end

app/views/delivery_templates/_form.html.erb
<div id="product-form" class="form">
  <%= form_for(@template, 
    :url => (@template.id.blank? ? delivery_templates_path : delivery_template_path(@template)), 
    :html => {:class => 'form-horizontal'}) do |f| %>
  
    <% unless f.error_messages.blank? %>
      <div class="alert alert-error">
        <%= f.error_messages %>
      </div>
    <% end %>
        
    <div class="control-group"><label class="control-label">选择模板</label>
      <div class="controls">
        <%= f.select :template, LOGISTICS_COMPANIES.map{|k, v| [v[:name], k]}, :class => 'input-small' %>
      </div>
    </div>
    
    <div class="control-group"><label class="control-label">模板名称</label>
      <div class="controls">
        <%= f.text_field :name, :class => 'input-medium' %>
      </div>
    </div>

    <!-- <div class="control-group"><label class="control-label">物流公司</label>
      <div class="controls">
        <%= f.select :company, LOGISTICS_COMPANIES.map{|k, v| [v[:name], k]}, 
          {:include_blank => true}, :class => 'input-small' %>
      </div>
    </div> -->
    
    <!-- <div class="control-group"><label class="control-label">运单图片</label>
      <div class="controls">
        <%= file_field_tag :file, :class => 'span1' %>
      </div>
    </div> -->

    <div class="control-group"><label class="control-label">宽度</label>
      <div class="controls">
        <%= f.text_field :width, :class => 'input-mini' %>mm(毫米)
      </div>
    </div>

    <div class="control-group"><label class="control-label">高度</label>
      <div class="controls">
        <%= f.text_field :height, :class => 'input-mini' %>mm(毫米)
      </div>
    </div>
    
    <div class="control-group"><label class="control-label">默认</label>
      <div class="controls">
        <%= f.check_box :default, :class => 'input-mini' %>
      </div>
    </div>
    
    <div class="control-group"><label class="control-label">选择打印项</label>
      <div class="controls" id='template-fields-select'>
        <% TEMPLATE_OPTIONS.each_with_index do |item, index| %>
          <label class="checkbox inline" style=''>
            <input type="checkbox" data-id='<%=item[0]%>' 
              name='fields[<%=item[0]%>]' value="<%=item[0]%>"/>
            <span><%= item[1] %></span>
          </label>
          <% if index%5 == 4 %>
            <br/>
          <% end %>
        <% end %>
      </div>
    </div>
    
    <h4 style='margin-left:50px;'>打印偏移调整：</h4>
    
    <div id='template-container' class='hide' style='margin-left:50px;position: relative'>
      <%= image_tag '#', :size => '766x424', :id => 'template-image' %>
    </div>
    
    <div class="form-actions">
      <%= f.submit " 保存　", :class => "btn btn-success" %>&nbsp;&nbsp;
      <%= link_to '取消', products_path, :class => 'btn' %>
    </div>
  <% end %>
</div>

<script>
  jQuery(function($) {
    var templateContainer = $('#template-container');
    var templateImage = $('#template-image');
    var templateSelect = $('#delivery_template_template');
    var templateFieldsSelect = $('#template-fields-select');

    // 更换图片
    var changeTemplateImage = function(template) {
      var imageUrl = '/images/templates/' + template + '.jpg';
      templateImage.attr('src', imageUrl);
      templateContainer.show();
      
      var input = $('<input type="hidden"/>')
                    .attr('name', 'delivery_template[image_url]')
                    .val( imageUrl );
                    
      templateContainer.append(input);
    }
    
    // 更换打印选项
    var changeTemplateFields = function(fields) {
      templateFieldsSelect.find('input').attr('checked', false);
      // var fields = _.find(TEMPLATES, function(t){ return t.ename == template; }).fields;

      templateFieldsSelect.find('input').each(function() {
        var $this = $(this);  

        if( _.include(fields, $this.attr('data-id')) ) {
          $this.attr('checked', true);
        }
      });
    }
    
    // 得到一个元素的位置数据
    var getPosition = function(el) {
      // return 'width:' + el.css('width') + ';' + 'height:' + el.css('height') + ';'
      //         + 'top:' + el.css('top') + ';' + 'left:' + el.css('left');
      var result = '{' +
        'name: "'   + el.attr('data-name') + '",' +
        'width: "'  + el.css('width') + '",' +
        'height: "' + el.css('height') + '",' +
        'left: "'   + el.css('left') + '",' +
        'top: "'    + el.css('top') + '"' +
      '}';
      return result;
    }
		
    // 渲染编辑条
    var renderLabel = function(option) {
      var text = TEMPLATE_FIELDS[option.name];
      var cssObj = {
        'position': 'absolute',
        'width': option.width, 
        'height': option.height,
        'top': option.top,
        'left': option.left
      };
      
      console.debug(option, option.name, text, cssObj);
      var div = $('<div></div>')
                  .addClass('draggable')
                  .text(text)
                  .attr('id', 'field-' + option.name)
                  .attr('data-name', option.name)
                  .css(cssObj);
                  
      div.draggable({
        stop: function() {
  				$('#field-position-' + option.name).val(getPosition(div));
  			}
      });
      
      var input = $('<input type="hidden"/>')
                    .attr('id', 'field-position-' + option.name)
                    .attr('name', 'field_position[' + option.name + ']')
                    .val( getPosition(div) );
                    
      templateContainer.append(div);
      templateContainer.append(input);
    }

    // 渲染打印项编辑条
    var renderTemplateLabels = function(options) {
      _.each(options, function(option) {
        renderLabel(option);
      });
    }
    
    templateSelect.change(function() {
      var $this = $(this);

      templateContainer.find('.draggable').remove();
      templateContainer.find('input').remove();
      
      changeTemplateImage($this.val());

      var template = $this.val();

      var fields = _.find(TEMPLATES, function(t){ return t.ename == template; }).fields;
      changeTemplateFields(fields);
      
      var options = _.find(TEMPLATES, function(t){ return t.ename == template; }).options;
      renderTemplateLabels(options);
    });
  
    <% if action_name == 'new' %>
      var defaultTemplate = templateSelect.val();
      var fields = _.find(TEMPLATES, function(t){ return t.ename == defaultTemplate; }).fields;
      var options = _.find(TEMPLATES, function(t){ return t.ename == defaultTemplate; }).options;      
    <% else %>
      var defaultTemplate = '<%=@template.template%>';
      var fields = <%= raw @template.fields %>;
      var options = <%= raw @options %>;
    <% end %>
      
    changeTemplateImage(defaultTemplate);
    changeTemplateFields(fields);
    renderTemplateLabels(options);
    
  });
  
</script>

app/views/delivery_templates/edit.html.erb
<div class='row'>
  <div class='span2'>
    <%= render 'shared/settings_sidebar' %>
  </div>
  
  <div class='span10'>
    <div class="tools" style='margin:10px 0;'>
      <%= link_to '返回运单模板首页', delivery_templates_path %>
    </div>
    
    <h2>编辑模板</h2>
    <br/>

    <%= render 'form' %>
  </div>
</div>

app/views/delivery_templates/index.html.erb
<style>
  .operations a,span{
    float:left;
  }
  form {
    margin:0px;padding:0px;
    float:left;
  }
  form input {
    margin:0px;padding:0px;
  }
</style>

<div class='row'>
  <div class='span2'>
    <%= render 'shared/settings_sidebar' %>
  </div>  
  
  <div class='span10'>
    <p></p>

    <% if notice %>
    <div class='alert'>
      <%= notice %>
    </div>
    <% end %>

    <% if @templates.empty? %>
      您还没有创建自己的运单打印模板，马上 
    <% end %>
    <%= link_to '创建模板', new_delivery_template_path %><br/>
    
    <% unless @templates.empty? %>
    <table class="table table-striped" style='width:500px;'>
      <thead>
        <tr>
          <th width=''>运单模板名称</th>
          <th width=''>物流公司</th>
          <th width=''>是否默认</th>
          <th>操作</th>
        </tr>
      </thead>

      <tbody>
        <% @templates.each do |item| %>
        <tr>

          <td> <%= item.name %> </td>
          <td> <%= item.company %> </td>
          <td> <%= item.human_default %> </td>
          <td class='operations'>
            <%= link_to '编辑', edit_delivery_template_path(item) %>
            <span>&nbsp;&nbsp;&nbsp;</span>
            
            <%= button_to('删除', delivery_template_path(item), :confirm => '确定删除吗？',
                    :method => "delete", :remote => true, :disable_with => '处理中...') %>
          </td>
        </tr>
        <% end %>
        
      </tbody>
    </table>
    <% end %>
    
  </div>
</div>

app/views/delivery_templates/new.html.erb
<div class='row'>
  <div class='span2'>
    <%= render 'shared/settings_sidebar' %>
  </div>
  
  <div class='span10'>
    <div class="tools" style='margin:10px 0;'>
      <%= link_to '返回运单模板首页', delivery_templates_path %>
    </div>
    
    <h2>创建模板</h2>
    <br/>

    <%= render 'form' %>
  </div>
</div>