config/routes.rb
Paidan::Application.routes.draw do
  resources :docs
    
  resources :deliveries do
    collection do
      get 'deliverying'
      get 'delivered'
      
      get 'edit_delivery'
      post 'save_address'
      post 'shipping_in_volume'
      
      get 'print_expresses'
      get 'print_goods'
    end
  end

  resources :customers do
    collection do 
      get 'level_setting'
      post 'save_level_setting'
    end
  end

  resources :products do
    member do
    end
    
    collection do
      get 'select_category'
      get 'category_children'
    end
  end

  resources :suppliers do
    member do
      get 'follow'
      put 'save_follow'
    end
  end
  
  resources :tasks do
  end
  
  resources :orders do
    member do
      get 'check'
      put 'save_check'
      
      get 'page'
      put 'save_page'

      get 'toggle_pass'
    
      post 'close'
    end
    
    collection do 
      get 'waiting_pay'
      get 'waiting_delivery'
      get 'delivery'
      get 'refunding'
      get 'successed'
      get 'need_comment'
      get 'closed'
      get 'three_months_ago'
      
      get 'delivery'
      
      get 'sync'
      get 'do_sync'
      
      get 'update_ship_fee'
      get 'remark'
    end
  end
  
  resources :auth do
    collection do 
      get 'bind_jingdong'
      get 'bind_taobao'
      get 'bind_paipai'
      get 'bind_yihaodian'
      get 'bind_vjia'
    end
  end
  
  resources :dashboard do
    collection do
      get 'recent_datas'
    end
  end
  
  scope 'settings' do
    resources :shops
    resources :delivery_templates
  end
    
  resources :partners
  
  match 'login' => 'partners#login', :as => :login
  match 'check_login' => 'partners#check_login', :as => :check_login
  match 'register' => 'partners#register'
  match 'logout' => 'partners#logout', :as => :logout  

  match 'import' =>  'orders#import'
  match 'do_import' => 'orders#do_import'
  match 'import_sent' =>  'orders#import_sent'
  match 'do_import_sent' => 'orders#do_import_sent'
  
  match 'taobao_callback' => 'auth#taobao_callback'
  match 'paipai_callback' => 'auth#paipai_callback'
  match 'jingdong_callback' => 'auth#jingdong_callback'
  
  root :to => 'dashboard#index'

end

app/models/product.rb
# -*- encoding : utf-8 -*-

require 'paipai'

class Product < ActiveRecord::Base

  has_one :content, :class_name => 'ProductContent', :foreign_key => 'product_id'
  accepts_nested_attributes_for :content

  has_many :skus
  accepts_nested_attributes_for :skus
  
  has_many :properties
  accepts_nested_attributes_for :properties
  
  belongs_to :partner
  belongs_to :category

  validates_presence_of :name, :title, :price, :market_price, :custom_id, :num
  validates_uniqueness_of :custom_id, :scope => :partner_id
  validates_numericality_of :market_price, :greater_than => 0, :message => '必须大于0'
  validates_numericality_of :price, :greater_than => 0, :less_than_or_equal_to => :market_price, :message => '必须小于或等于商场价，并且大于0'
  
  validate do |record|
    record.errors[:base] << "至少要录入一款sku" if skus.empty?
  end
  
  # 集成上传模块
  mount_uploader :image1, ProductImageUploader
  mount_uploader :image2, ProductImageUploader
  mount_uploader :image3, ProductImageUploader
  mount_uploader :image4, ProductImageUploader
  mount_uploader :image5, ProductImageUploader
  
  STATUS = {
    :onsale => {
      :name => '出售中',
      :value => 10,
    },
    :instock => {
      :name => '仓库中',
      :value => 20,
    },
    :sale_on_time => {
      :name => '定时上架',
      :value => 30,
    }
  }
  
  STATUS_MAPPING = {
    :taobao => {
      'onsale' => 10,
      'instock' => 20,
    },
    :paipai => {
      'IS_FOR_SALE' => 10,
      'IS_IN_STORE' => 20,
      'IS_SALE_ON_TIME' => 30,
    },
    :jingdong => {
      
    },
  }
  
  def build_properties_values
    property1 = properties.build(:name => '颜色')
    ['红色', '绿色', '蓝色', '黑色', '黄色', '白色'].each do |name|
      property1.property_values.build :name => name
    end
  
    property2 = properties.build(:name => '尺码')
    ['XS', 'S', 'M', 'L', 'XL', 'XXL', '均码'].each do |name|
      property2.property_values.build :name => name
    end
  end
  
  class << self
    
    def shortage
      order("id DESC")
    end
    
  end
  
  
end

app/controllers/products_controller.rb
# encoding: UTF-8
class ProductsController < ApplicationController
  
  before_filter :filter_products, :only => [:index, :instock, :smart_sale]
  
  def filter_products
    @products = @current_partner.products.includes(:skus).order('id DESC').paginate(:page => params[:page], :per_page => 20)

    unless params[:q].blank?
      @products = @products.where("outer_id = '#{params[:q].strip}' or name like '%#{params[:q].strip}%'")
    end
    
    unless params[:min].blank?
      @shortage_skus = Sku.where("quantity < ?", params[:min].to_i)
      @products = @products.where(:id => @shortage_skus.map{ |sku| sku.product_id } )
    else
      @shortage_skus = []
    end
  end
  
  def index  
    # @products = @products.where(:status => Product::STATUS[:onsale][:value])
    
    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end
  
  def instock
    @products = @products.where(:status => Product::STATUS[:instock][:value])
    respond_to do |format|
      format.html { render :index }
      format.json
    end
  end

  def inventory
    @products = Product.order('id DESC').paginate(:page => params[:page], :per_page => 20)

    unless params[:q].blank?
      @products = @products.where("outer_id = '#{params[:q].strip}' or name like '%#{params[:q].strip}%'")
    end

    unless params[:min].blank?
      @products = @products.where("total < ?", params[:min].to_i)
    end
    
  end
  
  def edit_inventory
    @product = Product.find(params[:id])
  end

  def shortage
    @products = Product.shortage.paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end
  
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json
    end
  end
  
  def select_category
    @root_categories = Category.where('parent_id is null')
    render :layout => 'no_nav'
  end
  
  def category_children
    @categories = Category.where(:parent_id => params[:parent_id])
    render :layout => false
  end
  
  def new
    if params[:category_id].blank?
      redirect_to select_category_products_url, :notice => '请选择品类' 
      return
    end
    
    @product = Product.new
    @product.category_id = params[:category_id]
    @product.build_content
    @product.build_properties_values
    
    render :layout => 'no_nav'
  end
  
  def edit
    @product = Product.find(params[:id])
    @product.build_properties_values
    
    render :layout => 'no_nav'
  end
  
  def create
    if params[:product][:skus_attributes]
      params[:product][:skus_attributes].each do |key, value|
        value[:specification] = [
          {
            :property_id => '1001',
            :property => "颜色",
            :value_id => 10010001,
            :value => value.delete('value_0'),
          },
          {
            :property_id => '1002',
            :property => "尺码",
            :value_id => 10010002,
            :value => value.delete('value_1'),
          }
        ].to_json
      end
    end
    
    params[:product][:properties_attributes] = {}

    @product = Product.new(params[:product])
    @product.status = 20
    @product.is_delete = 20
    @product.audit_status = 10
    @product.partner_id = @current_partner.id
    
    @product.image1 = params[:image1]
    @product.image2 = params[:image2]
    @product.image3 = params[:image3]
    @product.image4 = params[:image4]
    @product.image5 = params[:image5]
    
    respond_to do |format|
      if @product.save
        format.html { redirect_to(edit_product_path(@product), :notice => '保存成功。') }
        format.json
      else
        @product.build_content
        @product.build_properties_values
        format.html { render :action => "new" }
        format.json
      end
    end
  end
  
  # 更新商品
  def update
    @product = Product.find(params[:id])
    
    if params[:product][:skus_attributes]
      params[:product][:skus_attributes].each do |key, value|
        value[:specification] = [
          {
            :property_id => '1001',
            :property => "颜色",
            :value_id => 10010001,
            :value => value.delete('value_0'),
          },
          {
            :property_id => '1002',
            :property => "尺码",
            :value_id => 10010002,
            :value => value.delete('value_1'),
          }
        ].to_json
      end
    end
    params[:product][:properties_attributes] = {}

    respond_to do |format|
      if @product.skus.delete_all and @product.update_attributes(params[:product])
        format.html { redirect_to(edit_product_path(@product), :notice => '保存成功') }
        format.json
      else
        format.html { render :action => "edit" }
        format.json
      end
    end
  end
  
  # 更新库存
  def update_inventory
    @product = Product.find(params[:id])

    respond_to do |format|
      num = Product.update_inventory(@product, params[:product])
      if num
        @product.update_attributes params[:product].merge(:num => num)
        
        format.html { redirect_to(edit_inventory_product_path(@product), :notice => '修改成功') }
        format.json
      else
        format.html { redirect_to(edit_inventory_product_path(@product), :notice => '') }
        format.json
      end
    end
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_path,:notice => "删除成功。") }
      format.json
    end
  end
  
  def stocks
    @products = Product.order('id DESC').paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end
  
  def sync
    # if cookies[:last_sync_time] and Time.at(cookies[:last_sync_time].to_i)  > 5.minutes.ago
    #   redirect_to products_path, :notice => '两次同步时间间隔不能小于5分钟！' and return
    # end

    cookies[:last_sync_time] = Time.now.to_i
        
    Product.sync(@current_user.id, @current_user.shops.binded)
    redirect_to :action => :index
  end
  
  def listing
    Product.do(:listing, params[:ids].split(','))
    redirect_to instock_products_path
  end
  
  def delisting
    Product.do(:delisting, params[:ids].split(','))
    redirect_to products_path
  end
end

app/helpers/products_helper.rb
# encoding: utf-8

module ProductsHelper
  
end

app/views/products/_custom_properties.html.erb
<%= f.fields_for :properties do |builder| %>
  <%= builder.text_field :name, :class => "properties-input span1", 
    :readonly => true, 'data-property' => builder.object.name %>
  <br/><br/>
  
  <%= builder.fields_for :property_values do |b| %>
    <%= check_box_tag :check_property, '', false, :class => 'check-property-value', 
      'data-property' => builder.object.name, 
      'data-property-value' => b.object.name  %>
    <%= b.object.name %>&nbsp;&nbsp;
  <% end %>
  <br/><br/>
<% end %>

<table id='skus-table' class='table table-striped table-condensed span4'>
  <thead>
    <tr>
      <th>颜色</th>
      <th>尺码</th>
      <th>价格</th>
      <th>库存</th>
      <th>商家编码</th>
    </tr>
  </thead>
  
  <tbody id='skus-tbody'>
    <%= f.fields_for :skus do |builder| %>
    <tr>
      <td><%= builder.text_field :value_0, :class => 'input-mini', :readonly => true %></td>
      <td><%= builder.text_field :value_1, :class => 'input-mini', :readonly => true %></td>
      <td><%= builder.text_field :price, :class => 'input-mini' %></td>
      <td><%= builder.text_field :num, :class => 'input-mini' %></td>
      <td><%= builder.text_field :custom_id, :class => 'input-mini' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<script>
  $(document).ready(function(){
    App.Views.Products.CustomProperties.init();
  });
</script>

app/views/products/_form.html.erb
<% if notice %>
<div class='alert alert-success'>
  <%= notice %>  <button class="close" data-dismiss="alert">×</button>
</div>
<% end %>

<div id="product-form" class="form">
  <%= form_for(@product, 
    :url => (@product.id.blank? ? products_path : product_path(@product)), :html => {:class => 'form-horizontal', :multipart => true}) do |f| %>
    
    <%= f.hidden_field :category_id %>
  
    <% unless f.error_messages.blank? %>
      <div class="alert alert-error">
        <%= f.error_messages %>
      </div>
    <% end %>
    
    <div class="control-group" style='color:red'>
      <label class="control-label" style='margin-top:-5px;'>品类</label>
      <div class="controls">
        <%= @product.category.parent.name %> &nbsp;>> &nbsp;
        <%= @product.category.name%>
      </div>
    </div>

    <div class="control-group"><label class="control-label">产品名称</label>
      <div class="controls">
        <%= f.text_field :name, :class => 'span3 ' %>
      </div>
    </div>
    
    <div class="control-group"><label class="control-label">产品标题</label>
      <div class="controls">
        <%= f.text_field :title, :class => 'span5 ' %>
      </div>
    </div>

    <div class="control-group"><label class="control-label">自定义编码</label>
      <div class="controls">
        <%= f.text_field :custom_id, :class => 'span1' %>
      </div>
    </div>
    
    <div class="control-group"><label class="control-label">自定义属性</label>
      <div class="controls">
        <%= render 'custom_properties', :f => f %>
      </div>
    </div>

    <div class="control-group"><label class="control-label">商场价</label>
      <div class="controls">
        <%= f.text_field :market_price, :class => 'span1' %>
      </div>
    </div>
    
    <div class="control-group"><label class="control-label">售卖价</label>
      <div class="controls">
        <%= f.text_field :price, :class => 'span1' %>
      </div>
    </div>
    
    <div class="control-group"><label class="control-label">数量</label>
      <div class="controls">
        <%= f.text_field :num, :class => 'span1 ' %>
      </div>
    </div>
    
    <div class="control-group"><label class="control-label">商品所在地</label>
      <div class="controls">
        <%= text_field :foo, :place, :class => 'span1 ' %>
      </div>
    </div>

    <div class="control-group"><label class="control-label">运费</label>
      <div class="controls">
        <%= text_field :foo, :ship_fee, :class => 'span1 ' %>
      </div>
    </div>

    <div class="control-group"><label class="control-label">是否组合促销</label>
      <div class="controls">
        <%= f.check_box :is_group_promotion, :class => 'span1 ' %>
      </div>
    </div>
    
    <div class="control-group"><label class="control-label">组合促销金额</label>
      <div class="controls">
        <%= f.text_field :group_promotion, :class => 'span1 ' %>
      </div>
    </div>
    
    <%= render 'image_fields', :f => f, :product => @product %>
    
    <div class="control-group"><label class="control-label">商品描述</label>
      <div class="controls">
        <%= f.fields_for :content do |builder| %>
          <%= builder.kindeditor :description, :width => 700, :height => 600 %>
        <% end %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit " 提交 ", :class => "btn btn-success" %>&nbsp;&nbsp;
      <%= link_to '取消', products_path, :class => 'btn' %>
    </div>
  <% end %>
</div>

app/views/products/_image_fields.html.erb
<div class="control-group"><label class="control-label">商品图片1</label>
  <div class="controls">
    <%= f.file_field :image1 %>
    <% if product.image1.url %>
      <%= image_tag product.image1.url, :size => '50x50' %>
    <% end %>
  </div>
</div>

<div class="control-group"><label class="control-label">商品图片2</label>
  <div class="controls">
    <%= f.file_field :image2 %>
    <% if product.image2.url %>
      <%= image_tag product.image2.url, :size => '50x50' %>
    <% end %>
  </div>
</div>

<div class="control-group"><label class="control-label">商品图片3</label>
  <div class="controls">
    <%= f.file_field :image3 %>
    <% if product.image3.url %>
      <%= image_tag product.image3.url, :size => '50x50' %>
    <% end %>
  </div>
</div>

<div class="control-group"><label class="control-label">商品图片4</label>
  <div class="controls">
    <%= f.file_field :image4 %>
    <% if product.image4.url %>
      <%= image_tag product.image4.url, :size => '50x50' %>
    <% end %>
  </div>
</div>

<div class="control-group"><label class="control-label">商品图片5</label>
  <div class="controls">
    <%= f.file_field :image5 %>
    <% if product.image5.url %>
      <%= image_tag product.image5.url, :size => '50x50' %>
    <% end %>
  </div>
</div>

app/views/products/category_children.html.erb
<%= select_tag "category_id", 
  options_from_collection_for_select(@categories, "id", "name"),
  :class => 'min', :multiple => "multiple" %>

app/views/products/edit.html.erb
<h2>编辑产品</h2>
<br/>

<%= render 'form' %>

app/views/products/edit_inventory.html.erb
<div class='row'>
  <div class='span2'>
    <%= render 'sidebar' %>
  </div>  
  
  <div class='span10'>

    <div class="tools" style='margin:10px 0;'>
      <%= link_to '返回商品管理页面', products_path, :class => "" %>&nbsp;&nbsp;
    </div>
    <h2>调整库存 <small> <%= @product.name %>  (总库存：<%= @product.total %>)</small></h2><br/>
    
    <% if notice %>
    <div class="alert alert-success">
      <a class="close" data-dismiss="alert">×</a>
      <strong><%= notice %></strong>
    </div>
    <% end %>
    <script>
      jQuery(function($) {
        $(".alert").alert()        
      });
    </script>

    
    <%= form_for @product, :url => update_inventory_product_path(@product),:html=>{:class => "form-inline"} do |f| %>
    
      <%= f.error_messages %>
      
      <table class="table table-condensed">
        <thead>
          <tr>
            <th width='8%'>sku编码</th>
            <th width='20%'>规格</th>
            <th width='10%'>单价</th>
            <th width='10%'>库存</th>
          </tr>
        </thead>

        <tbody>
          <%= f.fields_for :skus do |builder| %>
          <tr>
            <td><%= builder.object.outer_id %></td>
            <td><%= builder.object.properties %></td>
            <td><strong><%= builder.object.price %></strong></td>
            <td>
              <%= builder.text_field :quantity, :class => 'span1' %>
              
              <%= builder.hidden_field :outer_id %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <p><%= f.submit " 确定 ", :class => 'btn btn-success' %></p>
    <% end %>
    
  </div>
</div>

app/views/products/edit_sale.html.erb
<div class='row'>
  <div class='span2'>
    <%= render 'sidebar' %>
  </div>  
  
  <div class='span10'>
    <div style='margin:15px 0;'>
      <h1>
        <span id='step1'>1. 选择商品</span>
          ->
        <span id='step1'>2. 设置上下架计划</span>
      </h1>
    </div>
  
    <%= link_to '<-上一步', smart_sale_products_path %>
    
    <%= form_for(:task, :url => '#', :html => {:class => 'form-inline'}) do |f| %>

      <% unless f.error_messages.blank? %>
        <div class="alert alert-error">
          <%= f.error_messages %>
        </div>
      <% end %>

      
      <div class="control-group" style='margin:20px 0 15px 6px;'>
        
        <div class="controls">
          <label class="control-label">计划名称：</label>
          <%= f.text_field :name, :class => 'span2' %>
        </div>
      </div>

      <%= image_tag 'edit-sale.png' %><br/>
      
      <%= f.submit ' 保存 ', :class => 'btn btn-success', :style => 'margin-left:300px;' %>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<% if notice %>
<div class='alert'>
  <%= notice %>  <button class="close" data-dismiss="alert">×</button>
</div>
<% end %>

<div class="row" style='margin-top: 10px; margin-bottom:6px;'>

  <div class="span8">

    <input class="span3" id="q-input" size="16" type="text" placeholder="输入编码或名称，回车"/>
    <span style='padding-top:'>&nbsp;&nbsp;&nbsp;&nbsp;
  </div>
</div>

<div id="products">

  <div style='background-color:#E5F4F9;padding: 7px 0px 7px 10px;border: 1px solid #FAEFE3;'>
    <%= link_to '全选', 'javascript:;', :id => 'check-all-yes' %>
    &nbsp;
    <%= link_to '全不选', 'javascript:;', :id => 'check-all-no'%>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

    <!-- <% if action_name == 'index' %>
      <%= link_to '手动下架', 'javascript:;', :id => 'delisting-button', 
        :class => 'btn ' %>&nbsp;&nbsp;
    <% end %>
    
    <% if action_name == 'instock' %>
      <%= link_to '手动上架', 'javascript:;', :id => 'listing-button', 
        :class => 'btn ' %>&nbsp;&nbsp;
    <% end %> -->
  </div>


  <table class="table table-striped">
    <thead>
      <tr>
        <th width='50'></th>
        <th width='100'>编码</th>
        <th width=''>产品名称</th>
        <th width='80'>品类</th>
        <th width='60'>商场价</th>
        <th width='60'>售卖价</th>
        <th width='60'>总库存</th>
        <th width='55'></th>
      </tr>
    </thead>

    <tbody>
    <% @products.each do |item| %>
    <!-- <tr style='background-color:#F1F7FB;border: 1px solid #DDD;'> -->
    <tr>
      <td colspan='2'>
        <input type='checkbox' data-id='<%=item.id%>'/>&nbsp;&nbsp;
        <%= item.custom_id %>
      </td>
      <td><strong><%= item.name %></strong></td>
      <td><%= item.category.try(:name) %></td>
      <td><%= item.market_price %></td>
      <td><%= item.price %></td>
      <td><%= item.num %></td>
      <td>
        <%= link_to '编辑', edit_product_url(item), :target => '_blank' %>
      </td>
    </tr>
  
    
    <% end %>

    </tbody>
  </table>
</div>

<%= will_paginate @products, :previous_label => '上一页', :next_label => '下一页', :class => 'digg_pagination' %>
  

app/views/products/select_category.html.erb
<h2>选择品类</h2>
<br/>

<% if notice %>
<div class="alert">
  <a class="close" data-dismiss="alert">×</a>
  <strong><%= notice %></strong>
</div>
<% end %>

<%=form_tag('/products/new', :method =>:get, :class => 'form-horizontal') do %>

  <div class="control-group">
    <div class="controls">

      <%= select_tag "first_level_category_id", 
        options_from_collection_for_select(@root_categories, "id", "name"),
        :class => 'min', :multiple => "multiple" %>
      <span></span>
    </div>
  </div>

  <div class="form-actions">
    <%= submit_tag " 下一步 ", :id => 'next-button', :class => "btn btn-success" %>&nbsp;&nbsp;
  </div>
<% end %>

<script>
  $(document).ready(function() {    
    App.Views.Products.SelectCategory.init();
  });
</script>

app/views/products/shortage.html.erb
<div class='row'>
  <div class='span2'>
    <%= render 'sidebar' %>
  </div>  
  
  <div class='span10'>

    <div class="row" style='margin-top: 10px; margin-bottom:6px;'>
      <div class="span4">
        <label style='float:left;padding-top:5px'>平台库存少于</label> 
        <div class="controls">
          <input class="span1" id="appendedInputButton" size="16" type="text"/>
          <span class="help-inline">的商品：</span>
        </div>
      </div>
          
      <div class="span2 offset4">
        <a href="<%= sync_products_path %>" class="btn btn-info">手动同步</a>
      </div>
    </div>

    <div id="products">
  
      <table class="table table-striped">
        <thead>
        <tr>
          <th width='8%'>编码</th>
          <th width='30%' colspan='2' align='center'>产品名称</th>
          <th width='10%'>单价</th>
          <th width='7%'>总库存</th>
          <th width=''>各平台库存</th>
          <th width='10%'> </th>
        </tr>
        </thead>

        <tbody>
        <% @products.each do |item| %>
        <tr>
          <td><%= item.outer_id %></td>
          <td><%= image_tag item.image_url, :size => '50x50' %></td>
          <td><strong><%= item.name %></strong></td>
          <td><%= item.price %></td>
          <td><%= item.total %></td>
          <td> 
            淘宝：1000；京东：234；范德萨：4333
          </td>
          <td>
            <div>
              <%= link_to '详细库存', edit_product_path(item.id) + '?return_url=' + products_path %><br/>
            </div>
          </td>
        </tr>
        <% end %>

        </tbody>
      </table>
    </div>
    
    <%= will_paginate @products, :previous_label => '上一页', :next_label => '下一页', :class => 'digg_pagination' %>
    
  </div>
</div>

<script>
  jQuery(function($) {
    $('#search-options-button').click(function() {
      var $this = $(this);
      
      if($('#search-options').attr('data-status') == 'hide') {
        $('#search-options').show();
        $('#search-options').attr('data-status', 'show');
      }else {
        $('#search-options').hide();
        $('#search-options').attr('data-status', 'hide');
      }
    });
  });
</script>

app/views/products/show.html.erb
<div class='row'>
  <div class='span2'>
    <%= render 'sidebar' %>
  </div>  
  
  <div class='span10'>

    <div class="tools" style='margin:10px 0;'>
      <%= link_to '返回库存管理首页', products_path, :class => "" %>&nbsp;&nbsp;
      <%= link_to '修改', edit_product_path(@product), :class => "" %>
    </div>
    <br/>

    <%= form_for :skus, :url => '', do |f| %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th width='8%'>编码</th>
        <th width='30%' colspan='2' align='center'>产品名称</th>
        <th width='10%'>总库存</th>
        <th width='7%'>总库存</th>
        <th width=''>各平台库存</th>
        <th width='10%'> </th>
      </tr>
      </thead>

      <tbody>
      <% @products.each do |item| %>
      <tr>
        <td><%= item.outer_id %></td>
        <td><%= image_tag item.image_url, :size => '50x50' %></td>
        <td><strong><%= item.name %></strong></td>
        <td><%= item.price %></td>
        <td><%= item.total %></td>
        <td> 
          <% item.skus.each do |sku| %>
            <%= sku.inspect %>
          <% end %>
          淘宝：1000；京东：234；范德萨：4333
        </td>
    
        <td>
          <div>
            <%= link_to '详细库存', product_path(item.id) %><br/>
          </div>
        </td>
      </tr>
      <% end %>

      </tbody>
    </table>
    <% end %>
    
  </div>
</div>

app/views/products/stocks.html.erb
<div class='row'>
  <div class='span2'>
    <%= render 'sidebar' %>
  </div>  
  
  <div class='span10'>

    <div class="tools" style='margin:10px 0;'>
      <a href="<%= new_product_path %>" class="btn btn-info">手动同步</a>
    </div>

    <div id="products">
  
      <table class="table table-striped">
        <thead>
        <tr>
          <th width='15%'>产品</th>
          <th width=''>库存</th>

          <th width='10%'> </th>
        </tr>
        </thead>

        <tbody>
        <% @products.each do |item| %>
        <tr>
          <td> 
            产品编码：<%= item.no %><br/>
            <strong><%= item.name %></strong><br/>
            <%= image_tag item.image_url %>
          </td>
          <td> 
            <strong>总库存：</strong><%= item.total %> <br/>
            <strong>详细库存：</strong><br/>
            <% item.skus.each do |sku| %>
              <%= sku.inspect %>
            <% end %>
          </td>
      
          <td>
            <div style='display: inline;'>
              <br/>
              <%= link_to '详情', product_path(item.id) %>
            </div>
          </td>
        </tr>
        <% end %>

        </tbody>
      </table>

    </div>
  </div>
</div>